AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  ita-ms4-statemgr SAM scaffold.

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 128
    Architectures:
      - x86_64
    Environment:
      Variables:
        LOG_LEVEL: INFO
        SERVICE_NAME: ms4-statemgr

Resources:
  StateMgrFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-statemgr-handler"
      CodeUri: src/
      Handler: main.handler

Outputs:
  FunctionArn:
    Description: Lambda ARN for ms4-statemgr.
    Value: !GetAtt StateMgrFunction.Arn

  FunctionName:
    Description: Lambda name for ms4-statemgr.
    Value: !Ref StateMgrFunction
