version = 0.1

[default]
[default.global.parameters]
stack_name = "ita-ms2-detection"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "eu-central-1"
profile = "dev"
parameter_overrides = "ProcessingBucketName=ita-data-pxuzz47kqx UploadedPhotosQueueArn=arn:aws:sqs:eu-central-1:186388857715:ita-uploaded-photos-pxuzz47kqx FacesExtractionQueueArn=arn:aws:sqs:eu-central-1:186388857715:ita-faces-extraction-pxuzz47kqx FacesExtractionQueueUrl=https://sqs.eu-central-1.amazonaws.com/186388857715/ita-faces-extraction-pxuzz47kqx Ms4InternalApiBaseUrl=https://90zby48wa9.execute-api.eu-central-1.amazonaws.com"

[default.package.parameters]
resolve_s3 = true
