AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  ita-ms1-ingress SAM scaffold.

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 128
    Architectures:
      - x86_64
    Environment:
      Variables:
        LOG_LEVEL: INFO
        SERVICE_NAME: ms1-ingress

Resources:
  IngressFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ingress-handler"
      CodeUri: src/
      Handler: main.handler

Outputs:
  FunctionArn:
    Description: Lambda ARN for ms1-ingress.
    Value: !GetAtt IngressFunction.Arn

  FunctionName:
    Description: Lambda name for ms1-ingress.
    Value: !Ref IngressFunction
